
[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/heroku/x"

[[constraint]]
  branch = "master"
  name = "github.com/junzh0u/httpx"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[prune]
  go-tests = true
  unused-packages = true
